import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login';
import { getSession } from "next-auth/react"
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';

export default function Home({session}) {

  // if (!session) return <Login />

  return (
    <div >
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1 className="text-2xl">Let's build facebook</h1> */}
      <Header />
      
      <main className="flex bg-gray-100">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  // get the user

  const session = await getSession(context);

  return {
    props: {
      session,
    }
  }
}
